### ISSUE TITLE
Set up our Kanban board

### ISSUE THREAD

**Issue by ZeenatLawal** [ZeenatLawal/Space-Travelers-Hub#25]
[Project Link](https://github.com/ZeenatLawal/Space-Travelers-Hub/projects/1)

Hello code reviewer, we have 2 members in our team✌

**Comment by henatan99** [comment]
Hi @ZeenatLawal && @julie-ify , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
